{"uid":"ad11ba32e6e098e3","name":"test_find_resend_link[ru]","fullName":"authorization.tests.test_verification_code.TestVerificationCodePassword#test_find_resend_link","historyId":"1f7200f2fbddc20ee50fcba9eba7b34c","time":{"start":1724590740980,"stop":1724590740980,"duration":0},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55d113c9f6ca <unknown>\n#1 0x55d113970600 <unknown>\n#2 0x55d1139a8485 <unknown>\n#3 0x55d1139a42f8 <unknown>\n#4 0x55d1139eece8 <unknown>\n#5 0x55d1139e2643 <unknown>\n#6 0x55d1139b2d31 <unknown>\n#7 0x55d1139b379e <unknown>\n#8 0x55d113c6725b <unknown>\n#9 0x55d113c6b1f2 <unknown>\n#10 0x55d113c54615 <unknown>\n#11 0x55d113c6bd82 <unknown>\n#12 0x55d113c3925f <unknown>\n#13 0x55d113c8ee68 <unknown>\n#14 0x55d113c8f040 <unknown>\n#15 0x55d113c9e49c <unknown>\n#16 0x7f8dda294ac3 <unknown>","statusTrace":"@pytest.fixture(scope=\"function\")\n    @allure.title('Инициализация драйвера Chrome')\n    def browser():\n        options = Options()\n        # options.add_argument(\"--headless\")\n        options.add_argument('--window-size=1920,1080')\n>       browser = webdriver.Chrome(options=options)\n\nconftest.py:41: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py:66: in __init__\n    super().__init__(command_executor=executor, options=options)\n/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:212: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:299: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:354: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fcaed693350>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: Chrome failed to sta...\\\\n#14 0x55d113c8f040 \\\\u003Cunknown>\\\\n#15 0x55d113c9e49c \\\\u003Cunknown>\\\\n#16 0x7f8dda294ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\nE         (session not created: DevToolsActivePort file doesn't exist)\nE         (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nE       Stacktrace:\nE       #0 0x55d113c9f6ca <unknown>\nE       #1 0x55d113970600 <unknown>\nE       #2 0x55d1139a8485 <unknown>\nE       #3 0x55d1139a42f8 <unknown>\nE       #4 0x55d1139eece8 <unknown>\nE       #5 0x55d1139e2643 <unknown>\nE       #6 0x55d1139b2d31 <unknown>\nE       #7 0x55d1139b379e <unknown>\nE       #8 0x55d113c6725b <unknown>\nE       #9 0x55d113c6b1f2 <unknown>\nE       #10 0x55d113c54615 <unknown>\nE       #11 0x55d113c6bd82 <unknown>\nE       #12 0x55d113c3925f <unknown>\nE       #13 0x55d113c8ee68 <unknown>\nE       #14 0x55d113c8f040 <unknown>\nE       #15 0x55d113c9e49c <unknown>\nE       #16 0x7f8dda294ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:229: SessionNotCreatedException","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1724590737419,"stop":1724590737453,"duration":34},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"Инициализация драйвера Chrome","time":{"start":1724590740981,"stop":1724590741166,"duration":185},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55d113c9f6ca <unknown>\n#1 0x55d113970600 <unknown>\n#2 0x55d1139a8485 <unknown>\n#3 0x55d1139a42f8 <unknown>\n#4 0x55d1139eece8 <unknown>\n#5 0x55d1139e2643 <unknown>\n#6 0x55d1139b2d31 <unknown>\n#7 0x55d1139b379e <unknown>\n#8 0x55d113c6725b <unknown>\n#9 0x55d113c6b1f2 <unknown>\n#10 0x55d113c54615 <unknown>\n#11 0x55d113c6bd82 <unknown>\n#12 0x55d113c3925f <unknown>\n#13 0x55d113c8ee68 <unknown>\n#14 0x55d113c8f040 <unknown>\n#15 0x55d113c9e49c <unknown>\n#16 0x7f8dda294ac3 <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/motherhash/motherhash/conftest.py\", line 41, in browser\n    browser = webdriver.Chrome(options=options)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"afterStages":[],"labels":[{"name":"subSuite","value":"6. По истечении 60 секунд появляется текст Didn't receive an email? / Не получили письмо? / Não recebeu o email?                        и ссылки с текстом Click to Resend / Нажмите, чтобы отправить повторно / Clique para reenviar под полями для ввода кода подтверждения"},{"name":"suite","value":"Verification Code"},{"name":"parentSuite","value":"authorization.tests"},{"name":"host","value":"fv-az1247-936"},{"name":"thread","value":"11832-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"authorization.tests.test_verification_code"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"language","value":"'ru'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":2,"unknown":0,"total":4},"items":[{"uid":"91ea57906ba87b0c","reportUrl":"https://konstantingerasimovwork.github.io/motherhash/106//#testresult/91ea57906ba87b0c","status":"passed","time":{"start":1724505309344,"stop":1724505369930,"duration":60586}},{"uid":"2f36269db3b9b54f","reportUrl":"https://konstantingerasimovwork.github.io/motherhash/105//#testresult/2f36269db3b9b54f","status":"passed","time":{"start":1724487014600,"stop":1724487075134,"duration":60534}},{"uid":"671e4759b99b7655","reportUrl":"https://konstantingerasimovwork.github.io/motherhash/104//#testresult/671e4759b99b7655","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55d9d445b6ca <unknown>\n#1 0x55d9d412c600 <unknown>\n#2 0x55d9d4164485 <unknown>\n#3 0x55d9d41602f8 <unknown>\n#4 0x55d9d41aace8 <unknown>\n#5 0x55d9d419e643 <unknown>\n#6 0x55d9d416ed31 <unknown>\n#7 0x55d9d416f79e <unknown>\n#8 0x55d9d442325b <unknown>\n#9 0x55d9d44271f2 <unknown>\n#10 0x55d9d4410615 <unknown>\n#11 0x55d9d4427d82 <unknown>\n#12 0x55d9d43f525f <unknown>\n#13 0x55d9d444ae68 <unknown>\n#14 0x55d9d444b040 <unknown>\n#15 0x55d9d445a49c <unknown>\n#16 0x7fd73ae94ac3 <unknown>","time":{"start":1724485954898,"stop":1724485954898,"duration":0}}]},"tags":[]},"source":"ad11ba32e6e098e3.json","parameterValues":["'ru'"]}